config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories, only: %i[index new create]
  resources :products do
    resources :reviews, only: %i[create]
  end

  resources :reviews do
    resources :comments, only: %i[create]
  end

  namespace :admin do
    root 'static_pages#home'
    resources :users
    resources :categories
    resources :products
    resources :reviews
    resources :comments
  end
end

app/controllers/admin/reviews_controller.rb
# frozen_string_literal: true

# Description/Explanation of Admin::ReviewsController class

class Admin::ReviewsController < AdminController
  before_action :find_review, only: %i[show edit update destroy]

  def index
    @admin_reviews = Review.all
  end

  def show;  end

  def new
    @admin_review = Review.new
  end

  def create
    @admin_review = Review.new(admin_review_params)

    if @admin_review.save
      redirect_to @admin_review, notice: 'Create review successfully.'
    else
      render :new
    end
  end

  def edit;  end

  def update
    if @admin_review.update(admin_review_params)
      redirect_to @admin_review, notice: 'Update review successfully.'
    else
      render :edit
    end
  end

  def destroy
    @admin_review.destroy
    redirect_to admin_reviews_url, notice: 'Delete review successfully'
  end

  private
    def admin_review_params
      params.require(:admin_review).permit :content, :rating
    end

    def find_review
      @admin_review = Review.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

# Description/Explanation of ReviewsController class

class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.user_id = current_user.id
    
    respond_to do |format|
      if @review.save
        html_comment_form = render_to_string(
          partial: 'comments/form',
          locals: { review: @review, comment: Comment.new }
        )
        @product.calculate_rating
        format.json { render json: review_serializer(html_comment_form), status: :created }
      else
        format.json { render json: @review.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit :content, :rating
    end

    def review_serializer(comment_form)
      {
        id: @review.id,
        content: @review.content,
        rating: @review.rating,
        user: {
          email: @review.user.email
        },
        product: {
          aggregate_rating: @product.reload.aggregate_rating
        },
        comment_form: comment_form
      }
    end

end

app/views/admin/reviews/_form.html.erb
<%= form_for Review.new ,url: admin_reviews_path do |f| %>
  <% if admin_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_review.errors.count, "error") %> prohibited this admin_review from being saved:</h2>

      <ul>
        <% admin_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :content, "Write your review below" %></br>
  <%= f.text_area :content, :rows => "4", :cols => "75" %>
  <%= f.label :rating, "Rate this product" %>
  <%= f.select(:rating, options_for_select([
    ["1", 1],
    ["2", 2],
    ["3", 3],
    ["4", 4],
    ["5", 5]
    ])) %></br>

  <div class="form-group">
    <%= f.label :user %>
    <%= f.collection_select :user_id, User.all, :id, :email, :prompt => 'Select one!' %>
  </div>

  <div class="form-group">
    <%= f.label :product %>
    <%= f.collection_select :product_id, Product.all, :id, :product_name, :prompt => 'Select one!' %>
  </div>
  <%= f.submit "Submit Review", class: "btn btn-info" %>
<% end %>

app/views/admin/reviews/edit.html.erb
<h1>Editing Admin Review</h1>

<%= render 'form', admin_review: @admin_review %>

<%= link_to 'Show', @admin_review, class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_reviews_path, class: 'btn btn-primary' %>

app/views/admin/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Rating</th>
      <th>User</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_reviews.each do |admin_review| %>
      <tr>
        <td><%= admin_review.content %></td>
        <td><%= admin_review.rating %></td>
        <td><%= admin_review.user_id %></td>
        <td><%= admin_review.product_id %></td>
        <td><%= link_to 'Show', admin_review, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_admin_review_path(admin_review), class: 'btn btn-primary' %></td>
        <td>
          <%= link_to 'Destroy', admin_review, method: :delete,
                              data: { confirm: 'Are you sure?' },
                              class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Review', new_admin_review_path, class: 'btn btn-primary' %>

app/views/admin/reviews/new.html.erb
<h1>New Admin Review</h1>

<%= render 'form', admin_review: @admin_review %>

<%= link_to 'Back', admin_reviews_path, class: 'btn btn-primary' %>

app/views/admin/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @admin_review.content %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @admin_review.rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @admin_review.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @admin_review.product_id %>
</p>

<%= link_to 'Edit', edit_admin_review_path(@admin_review), class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_reviews_path, class: 'btn btn-primary' %>