config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories, only: %i[index new create]
  resources :products do
    resources :reviews, only: %i[create]
  end

  resources :reviews do
    resources :comments, only: %i[create]
  end

  namespace :admin do
    root 'static_pages#home'
    resources :users
    resources :categories
    resources :products
    resources :reviews
    resources :comments
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }

  has_many :products, dependent: :destroy
  has_many :sub_categories, class_name: Category.name, foreign_key: :parent_id
  belongs_to :parent_category, class_name: Category.name, foreign_key: :parent_id, optional: true
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

# Description/Explanation of Admin::CategoriesController class

class Admin::CategoriesController < AdminController
  before_action :find_category, only: %i[show edit update destroy]

  def index
    @categories = Category.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params

    if @category.save
      redirect_to admin_category_path(@category), notice: 'Create category successfully'
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_url, notice: 'Delete category successfully'
  end

  def edit; end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_category_path(@category), notice: 'Updated category successfully'
    else
      render :edit
    end
  end

  def show;  end

  private
    def category_params
      params.require(:category).permit :name, :parent_id
    end

    def find_category
      @category = Category.find(params[:id])
    end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# Description/Explanation of CategoriesController class

class CategoriesController < ApplicationController
 def index
   @categories = Category.order(created_at: :desc)
 end
end

app/views/admin/categories/_form.html.erb
<%= form_for Category.new, url: admin_categories_path do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <label for="staticName" class="col-sm-2 col-form-label">Name</label>

    <div class="col-sm-10">
      <%= f.text_field :name, class:'form-control',placeholder:"Enter category's name" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, Category.all, :id, :name, :prompt => 'Select one!' %>
  </div>

  <div class="text-center">
    <%= f.submit 'Submit', class: "btn btn-info col-lg-12" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Admin Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', admin_category_path(@category), class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_categories_path, class: 'btn btn-primary' %>

app/views/admin/categories/index.html.erb
<div class="w-75 p-3">
  <div class="card-header">
    <div class="row">
      <div class="col-lg-9">
        <p id="notice"><%= notice %></p>
        <h3 class="text-center">Categories</h3>
      </div>

      <div class="col-lg-3">
        <%= link_to "Add Category", new_admin_category_path, class: 'btn btn-info pull-right' %>
        <%= link_to "Back", admin_root_path, class: 'btn btn-info pull-right' %>
      </div>
    </div>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Parent Category</th>
        <th>Creation time</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.parent_category&.name %></td>
          <td><%= category.created_at %></td>
          <td><%= link_to 'Show', admin_category_path(category), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-primary' %></td>
          <td>
            <%= link_to 'Destroy', admin_category_path(category), method: :delete,
                                                        data: { confirm: 'Are you sure?' },
                                                        class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <h1 class="text-center">Create category</h1>
      <%= render 'form', category: @category %>
      <%= link_to 'Home', admin_root_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @category.parent_id %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category), class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_categories_path, class: 'btn btn-primary' %>