config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories, only: %i[index new create]
  resources :products do
    resources :reviews, only: %i[create]
  end

  resources :reviews do
    resources :comments, only: %i[create]
  end

  namespace :admin do
    root 'static_pages#home'
    resources :users
    resources :categories
    resources :products
    resources :reviews
    resources :comments
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ActiveRecord::Base
  validates :product_name, presence: true, length: { minimum: 5 }
  validates :quantity, presence: true
  validates :unit_price, presence: true

  belongs_to :category
  has_many :reviews, dependent: :destroy

  def calculate_rating
    avg_review = self.reviews.average(:rating).round(2)
    self.update(aggregate_rating: avg_review)
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

# Description/Explanation of Admin::ProductsController class

class Admin::ProductsController < AdminController
  before_action :find_product, only: %i[show edit update destroy]

  def index
    @products = Product.all.order(:product_name)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params

    if @product.save
      redirect_to @product, notice: 'Product added!'
    else
      render :new
    end
  end

  def show;  end

  def edit;  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Update product successfully!'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_url, notice: 'Delete product successfully'
  end

  private
    def product_params
      params.require(:admin_product).permit :product_name, :quantity, :unit_price, :discontinued, :desc, :category_id
    end

    def find_product
      @product = Product.find(params[:id])
    end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Description/Explanation of ProductsController class

class ProductsController < ApplicationController
  def index
    @products = Product.all.order(:product_name)
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.order("created_at DESC")
    @review = @product.reviews.new
    @comment = @review.comments.new
  end

  private
    def product_params
      params.require(:product).permit :product_name, :quantity, :unit_price, :discontinued, :desc, :category_id
    end
end

app/views/admin/products/_form.html.erb
<%= form_for Product.new ,url: admin_products_path do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :product_name %>
    <%= f.text_field :product_name, placeholder: "Enter product name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.text_field :quantity, placeholder: "Enter the number of products", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :unit_price %>
    <%= f.text_field :unit_price, placeholder: "Enter unit price", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :discountinued %>
    <%= f.text_field :discontinued, placeholder: "Enter discountinued", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :desc %>
    <%= f.text_field :desc, placeholder: "Enter description", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name, :prompt => 'Select one!' %>
  </div>

  <div class="text-center">
    <%= f.submit "Create Product", class: "btn btn-info col-lg-12" %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Admin Product</h1>

<%= render 'form', admin_product: @admin_product %>

<%= link_to 'Show', @admin_product, class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_products_path, class: 'btn btn-primary' %>

app/views/admin/products/index.html.erb
<div class="w-75 p-3">
  <div class="card-header">
    <div class="row">
      <div class="col-lg-9">
        <h3 class="text-center">Products</h3>
      </div>

      <div class="col-lg-3">
        <%= link_to "Add Product", new_admin_product_path, class: 'btn btn-info pull-right' %>
        <%= link_to "Back", admin_root_path, class: 'btn btn-info pull-right' %>
      </div>
    </div>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Product name</th>
        <th>Category</th>
        <th>Quantity</th>
        <th>Unit price</th>
        <th>Units in stock</th>
        <th>Units on order</th>
        <th>Discontinued</th>
        <th>Aggregate rating</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.product_name %></td>
          <td><%= product.category.name %></td>
          <td><%= product.quantity %></td>
          <td><%= product.unit_price %></td>
          <td><%= product.unit_in_stock %></td>
          <td><%= product.unit_on_order %></td>
          <td><%= product.discontinued %></td>
          <td><%= product.aggregate_rating %></td>
          <td><%= link_to 'Show', admin_product_path(product), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_admin_product_path(product), class: 'btn btn-primary' %></td>
          <td>
            <%= link_to 'Destroy', admin_product_path(product), method: :delete,
                                  data: { confirm: 'Are you sure?' },
                                  class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/products/new.html.erb
<div class="container-fluid h-100 bg-light text-dark">
  <div class="row justify-content-center align-items-center">
    <h1>Create Product</h1>
  </div>
  <div class="row justify-content-center align-items-center">
    <div class="col col-sm-6 col-md-6 col-lg-4 col-xl-3">
      <%= render 'form', product: @product %>
      <%= link_to 'Home', admin_root_path, class: 'btn btn-primary' %>
      <%= link_to 'Back', admin_categories_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <center><h2><%= @product.product_name %></h2></center>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td rowspan="2"><strong>Aggregate Rating:</strong></td>
                <td id="aggregate_rating">
                  <% @product.aggregate_rating.to_i.times do %>
                    <span class="star">★</span>
                  <% end %>
                  <% (5 - @product.aggregate_rating.to_i).times do %>
                    <span class="out-of">★</span>
                  <% end %>&ensp;
                  <strong>
                    <% if @product.reviews.count == 0 %>
                      0/5
                    <% else %>
                      <%= @product.aggregate_rating %> / 5
                    <% end %>
                  </strong>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="fas fa-user"></i>&ensp;
                  <em><%= "#{@product.reviews.count} reviews" %></em>
                </td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @product.desc %></td>
              </tr>
              <tr>
                <td><strong>Unit Price:</strong></td>
                <td>$<%= @product.unit_price %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Return to List products", admin_products_path, class: 'btn btn-primary' %> |
          <%= link_to 'Edit', edit_admin_product_path(@product), class: 'btn btn-primary' %> |
          <%= link_to 'Back', admin_products_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>