config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories, only: %i[index new create]
  resources :products do
    resources :reviews, only: %i[create]
  end

  resources :reviews do
    resources :comments, only: %i[create]
  end

  namespace :admin do
    root 'static_pages#home'
    resources :users
    resources :categories
    resources :products
    resources :reviews
    resources :comments
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :role, presence: true, inclusion: { in: ['admin', 'user'] }
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

# Description/Explanation of Admin::UsersController class

class Admin::UsersController < AdminController
  before_action :find_user, only: %i[show edit update destroy]

  def index
    @admin_users = User.order(:id)
  end

  def show;  end

  def new
    @admin_user = User.new
  end

  def edit;  end

  def create
    @admin_user = User.new(admin_user_params)

    if @admin_user.save
      redirect_to @admin_user, notice: 'Create user successfully.'
    else
      render :new
    end
  end

  def update
    if @admin_user.update(admin_user_params)
      redirect_to @admin_user, notice: 'Update user successfully.'
    else
      render :edit
    end
  end

  def destroy
    @admin_user.destroy
    redirect_to admin_users_url, notice: 'Delete user successfully'
  end

  private
    def admin_user_params
      params.require(:admin_user).permit :email, :password, :password_confirmation
    end

    def find_user
      @admin_user = User.find(params[:id])
    end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Description/Explanation of UsersController class

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in @user
      remember @user
      flash[:success] = 'Successfully register'
      redirect_to root_path
    else
      flash.now[:alert] = 'Register failed'
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit :email, :password, :password_confirmation
    end
end

app/views/admin/users/_form.html.erb
<%= form_for User.new ,url: admin_users_path do |form| %>
  <% if admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
        <% admin_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Show', @admin_user, class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_users_path, class: 'btn btn-primary' %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.email %></td>
        <td><%= admin_user.password %></td>
        <td><%= admin_user.password_confirmation %></td>
        <td><%= link_to 'Show', admin_user_path(admin_user), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(admin_user), class: 'btn btn-primary' %></td>
        <td>
          <%= link_to 'Destroy', admin_user_path(admin_user), method: :delete,
                            data: { confirm: 'Are you sure?' },
                            class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin User', new_admin_user_path, class: 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<h1>New Admin User</h1>
<%= render 'form', admin_user: @admin_user %>
<%= link_to 'Back', admin_users_path, class: 'btn btn-primary' %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @admin_user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin_user.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @admin_user.password_confirmation %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user), class: 'btn btn-primary' %> |
<%= link_to 'Back', admin_users_path, class: 'btn btn-primary' %>